language: java
jdk: openjdk8
sudo: false

cache:
  yarn: true
  directories:
  - $HOME/.m2
  - view/node

env:
  - RUN_SLOW_TESTS=false
  - RUN_SLOW_TESTS=true

before_install:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- gem install dpl --source http://rubygems.org
- source scripts/travis/travis_rc.sh
- chmod 600 deploy_rsa
- scripts/travis/before_script.sh

addons:
  mariadb: '10.2'

install: true

script:
- scripts/travis/build.sh

after_success:
- scripts/travis/after_script.sh

deploy:
- provider: script
  skip_cleanup: true
  script: scripts/travis/deploy.sh
  on:
    all_branches: true

