version: '3'
services:

  xcolab-view:
    build: view/
    image: xcolab-view
    network_mode: 'host'
    volumes:
      - '~/.xcolab.application.properties:/root/.xcolab.application.properties'

  eureka-server-xcolab:
    build: microservices/cloud/eureka-server/
    image: eureka-server-xcolab
    network_mode: 'host'


  activities-service-xcolab:
    build: microservices/services/activities-service/
    image: activities-service-xcolab
    network_mode: 'host'
    volumes:
      - '~/.xcolab.application.properties:/root/.xcolab.application.properties'
  admin-service-xcolab:
    build: microservices/services/admin-service/
    image: admin-service-xcolab
    network_mode: 'host'
    volumes:
      - '~/.xcolab.application.properties:/root/.xcolab.application.properties'
  comment-service-xcolab:
    build: microservices/services/comment-service/
    image: comment-service-xcolab
    network_mode: 'host'
    volumes:
      - '~/.xcolab.application.properties:/root/.xcolab.application.properties'
  content-service-xcolab:
    build: microservices/services/content-service/
    image: content-service-xcolab
    network_mode: 'host'
    volumes:
      - '~/.xcolab.application.properties:/root/.xcolab.application.properties'
  contest-service-xcolab:
    build: microservices/services/contest-service/
    image: contest-service-xcolab
    network_mode: 'host'
    volumes:
      - '~/.xcolab.application.properties:/root/.xcolab.application.properties'
  emails-service-xcolab:
    build: microservices/services/emails-service/
    image: emails-service-xcolab
    network_mode: 'host'
    volumes:
      - '~/.xcolab.application.properties:/root/.xcolab.application.properties'
  members-service-xcolab:
    build: microservices/services/members-service/
    image: members-service-xcolab
    network_mode: 'host'
    volumes:
      - '~/.xcolab.application.properties:/root/.xcolab.application.properties'
  modeling-service-xcolab:
    build: microservices/services/modeling-service/
    image: modeling-service-xcolab
    network_mode: 'host'
    volumes:
      - '~/.xcolab.application.properties:/root/.xcolab.application.properties'
  moderation-service-xcolab:
    build: microservices/services/moderation-service/
    image: moderation-service-xcolab
    network_mode: 'host'
    volumes:
      - '~/.xcolab.application.properties:/root/.xcolab.application.properties'
  search-service-xcolab:
    build: microservices/services/search-service/
    image: search-service-xcolab
    network_mode: 'host'
    volumes:
      - '~/.xcolab.application.properties:/root/.xcolab.application.properties'
  tracking-service-xcolab:
    build: microservices/services/tracking-service/
    image: tracking-service-xcolab
    network_mode: 'host'
    volumes:
      - '~/.xcolab.application.properties:/root/.xcolab.application.properties'