version: '3.5'
services:

  view-xcolab:
    image: mikirockerful/view-xcolab
    ports:
      - "18082:18082"
    networks:
      - xcolab-network
    volumes:
      - '~/.xcolab.application.properties:/root/.xcolab.application.properties'
      - '${FILES_UPLOAD_DIR?"Specify a path for user uploaded files in env variable FILES_UPLOAD_DIR"}:/var/xcolab-images/'
    restart: on-failure
    depends_on:
      - xcolab_mysql
    deploy:
      placement:
        constraints: [node.role == manager]

  eureka-server-xcolab:
    image: mikirockerful/eureka-server-xcolab
    networks:
      xcolab-network:
        aliases:
          - eureka-server


  activities-service-xcolab:
    image: mikirockerful/activities-service-xcolab
    networks:
      - xcolab-network
    volumes:
      - '~/.xcolab.application.properties:/root/.xcolab.application.properties'
    restart: on-failure
    depends_on:
      - eureka-server-xcolab
  admin-service-xcolab:
    image: mikirockerful/admin-service-xcolab
    networks:
      - xcolab-network
    volumes:
      - '~/.xcolab.application.properties:/root/.xcolab.application.properties'
    restart: on-failure
    depends_on:
      - eureka-server-xcolab
  comment-service-xcolab:
    image: mikirockerful/comment-service-xcolab
    networks:
      - xcolab-network
    volumes:
      - '~/.xcolab.application.properties:/root/.xcolab.application.properties'
    restart: on-failure
    depends_on:
      - eureka-server-xcolab
  content-service-xcolab:
    image: mikirockerful/content-service-xcolab
    networks:
      - xcolab-network
    volumes:
      - '~/.xcolab.application.properties:/root/.xcolab.application.properties'
    restart: on-failure
    depends_on:
      - eureka-server-xcolab
  contest-service-xcolab:
    image: mikirockerful/contest-service-xcolab
    networks:
      - xcolab-network
    volumes:
      - '~/.xcolab.application.properties:/root/.xcolab.application.properties'
    restart: on-failure
    depends_on:
      - eureka-server-xcolab
  emails-service-xcolab:
    image: mikirockerful/emails-service-xcolab
    networks:
      - xcolab-network
    volumes:
      - '~/.xcolab.application.properties:/root/.xcolab.application.properties'
    restart: on-failure
    depends_on:
      - eureka-server-xcolab
  members-service-xcolab:
    image: mikirockerful/members-service-xcolab
    networks:
      - xcolab-network
    volumes:
      - '~/.xcolab.application.properties:/root/.xcolab.application.properties'
    restart: on-failure
    depends_on:
      - eureka-server-xcolab
  modeling-service-xcolab:
    image: mikirockerful/modeling-service-xcolab
    networks:
      - xcolab-network
    volumes:
      - '~/.xcolab.application.properties:/root/.xcolab.application.properties'
    restart: on-failure
    depends_on:
      - eureka-server-xcolab
  moderation-service-xcolab:
    image: mikirockerful/moderation-service-xcolab
    networks:
      - xcolab-network
    volumes:
      - '~/.xcolab.application.properties:/root/.xcolab.application.properties'
    restart: on-failure
    depends_on:
      - eureka-server-xcolab
  search-service-xcolab:
    image: mikirockerful/search-service-xcolab
    networks:
      - xcolab-network
    volumes:
      - '~/.xcolab.application.properties:/root/.xcolab.application.properties'
    restart: on-failure
    depends_on:
      - eureka-server-xcolab
  tracking-service-xcolab:
    image: mikirockerful/tracking-service-xcolab
    networks:
      - xcolab-network
    volumes:
      - '~/.xcolab.application.properties:/root/.xcolab.application.properties'
    restart: on-failure
    depends_on:
      - eureka-server-xcolab

networks:
  xcolab-network:
    name: xcolab-network
